### PR TITLE
feature(autoprefix): Autoprefix css tree

### PR DESCRIPTION
**Pull request by srowhani**
**This project uses [semver](http://semver.org), please check the scope of this pr:**

- [ ] #none# - documentation fixes and/or test additions
- [ ] #patch# - backwards-compatible bug fix
- [x] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG
- Consume broccoli-autoprefixer

### CODE REVIEW

**Comment by sglanzer-fire** [comment]
Approved - oh boy is this overdue.  Any chance we can apply the same to consuming addons?

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-core/pull-request/437/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-core)

**Review by sglanzer-fire — APPROVED** [review]

**Comment by srowhani** [comment]
Hm- if all addons have frost-core as a dependency, we won't need to

**Comment by sglanzer-fire** [comment]
@srowhani can you confirm that?  I wouldn't be surprised if this only executes in the `core` tree

**Comment by srowhani** [comment]
I've tested in both consuming addons and apps :+1:

**Pull request merged**
