### PR TITLE
adding frost-checkbox and icons to core as a test component

### PR DESCRIPTION
**Pull request by rox163**
# fix

### CODE REVIEW

**Comment by sglanzer-fire** [comment]
Approved - nice to put this in motion

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-core/pull-request/2/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-core)

**Comment by rox163** [comment]
not sure why the Travis build is failing. 'npm test' passes locally. Some kind of firefox error in travis?

**Comment by sglanzer-fire** [comment]
We can check the logs after the next build finishes

**Comment by rox163** [comment]
still failing...same error

**Pull request merged**
