### PR TITLE
Make select dropdown more flexible with consuming DOM

### PR DESCRIPTION
**Pull request by sandersky**
# MINOR
# CHANGELOG
- **Added** [ember-elsewhere](https://github.com/ef4/ember-elsewhere) as a new dependency.
- **Changed** `frost-select` and `frost-multi-select` to render dropdown elsewhere in the DOM, using `ember-elsewhere`, in order to make them more flexible.
- **Changed** minimum Ember version from `2.1` to `2.3` since `ember-elsewhere` doesn't appear to work on versions prior to `2.3`.

### CODE REVIEW

**Comment by sglanzer-fire** [comment]
So the idea would be to decouple the dropdown from the surrounding DOM so that we could overflow a container if necessary?  Makes sense, but I think we should also keep a local target so that we can choose to constrain the overflow - e.g. if I want the dropdown to open upward instead of overflowing the parent bounds.

**Comment by sglanzer-fire** [comment]
@juwara0 I can't remember if you guys have started the `select` tests yet, but if not be sure to pull this prior to that

**Comment by sglanzer-fire** [comment]
Approved - just need to address the travis failure and if possible I'd like to see the local target added (or an issue raised)

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-core/pull-request/200/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-core)

**Comment by juwara0** [comment]
@sglanzer We have not started the select tests yet.

**Comment by sglanzer-fire** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-core/pull-request/200/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-core)

**Comment by sglanzer-fire** [comment]
Approved - you're a beast

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-core/pull-request/200/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-core)

**Pull request merged**
