### PR TITLE
#388 Tabbing with select

### LINKED ISSUE #388: Tabbing with select
It seems you can begin typing into the select dropdown filter and then tab out of the select, moving focus to other inputs/links on the page. However at this point the dropdown is still visible making it hard to close without using a mouse. We need to make sure hitting tab while in the dropdown closes the dropdown under all scenarios.

### PR DESCRIPTION
**Pull request by srowhani**
**This project uses [semver](http://semver.org), please check the scope of this pr:**

- [x] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

Fixes #388 

# CHANGELOG
- Pass action closure `closeDropDown` into `frost-select-dropdown`

### CODE REVIEW

**Comment by job13er** [comment]
@srowhani Looks like some `frost-multi-select` tests are failing now

**Comment by job13er** [comment]
@srowhani A bugfix it's a bugfix without a test. Please include a test that fails b/c of the bug and passes now that there's a fix.

**Review by job13er — CHANGES_REQUESTED** [review]
@srowhani A bugfix it's a bugfix without a test. Please include a test that fails b/c of the bug and passes now that there's a fix.

**Comment by sglanzer-fire** [comment]
Seems reasonable, but I agree with Adam that I'd like to see a test added

**Pull request closed without merging**
