### PR TITLE
Add ember-spread to core

### PR DESCRIPTION
**Pull request by dafortin**
**This project uses [semver](http://semver.org), please check the scope of this pr:**

- [ ] #patch# - backwards-compatible bug fix
- [x] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG
* **Added** `ember-spread` to core components

### CODE REVIEW

**Comment by rox163** [comment]
:+1:

**Comment by quincyle** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-core/pull-request/331/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-core)

**Comment by sglanzer-fire** [comment]
This is a monumental number of changes to have completed in a day, nice work!

**Comment by sglanzer-fire** [comment]
Was the link the only component that couldn't have full options passed (currently)?

**Comment by dafortin** [comment]
@sglanzer No all the actions cannot be passed and the radio group/button looks a bit weird

**Comment by sglanzer-fire** [comment]
@dafortin can you give me a list of the things that are missing?  What does "a bit weird" mean?

**Comment by dafortin** [comment]
@sglanzer 

1) The link first 2 parameters
2) Radio group/button looks like this
```
{{#frost-radio-group
  options=(hash
    id='radioGroup1'
    selectedValue='b'
  )
  as |controls|
}}
  {{#controls.button
    options=(hash
      size='medium'
    )
    value='b'
  }}
    My label for b
  {{/controls.button}}
{{/frost-radio-group}}
```
If I'm adding value in the options the selection of the default value is not working.

Everything else looks ok.

**Comment by sglanzer-fire** [comment]
@dafortin Doesn't radio-group have a property for an array of values?  I was pretty sure it had an inline version

**Comment by sglanzer-fire** [comment]
@dafortin Also, would you mind raising issues for those 3 things (link, actions, radio) and assigning them to me?

**Comment by dafortin** [comment]
@sglanzer 
raised the issues on core?
Yes, there is an inline version why?

**Comment by sglanzer-fire** [comment]
Thought the inline version would cover your case, but I'll investigate - yes issues against core would be ideal

**Comment by dafortin** [comment]
@sglanzer #333 #332 #331

**Pull request merged**
