### PR TITLE
Move notification z-index above modal z-index

### PR DESCRIPTION
**Pull request by EWhite613**
**This project uses [semver](http://semver.org), please check the scope of this pr:**

- [ ] #none# - documentation fixes and/or test additions
- [x] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG
* Set notification z-index to appear above modals

### CODE REVIEW

**Comment by EWhite613** [comment]
Reference: https://github.com/ciena-frost/ember-frost-notifier/pull/41

**Comment by sglanzer-fire** [comment]
Makes sense to me - I'll just confirm this with UX

**Comment by sglanzer-fire** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-core/pull-request/458/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-core)

**Comment by sglanzer-fire** [comment]
Approved - Adjusted navigation to just below app bar per UX

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-core/pull-request/458/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-core)

**Pull request merged**
