### PR TITLE
Release 1.0.0

### PR DESCRIPTION
**Pull request by dafortin**
**This project uses [semver](http://semver.org), please check the scope of this pr:**

- [ ] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [x] #major# - incompatible API change

# CHANGELOG
- **UPDATED/ADDED** test suite for frost-button, frost-checkbox, frost-events, frost-icon, frost-link, frost-loading, frost-password, frost-radio-button, frost-group, frost-scroll, frost-text, frost-textarea, frost-toggle, utils
- **UPDATED** README for frost-button, frost-checkbox, frost-events, frost-icon, frost-link, frost-loading, frost-password, frost-radio-button, frost-group, frost-scroll, frost-text, frost-textarea, frost-toggle
- **UPDATED/ADDED** demo app for frost-button, frost-checkbox, frost-icon, frost-link, frost-loading, frost-password, frost-radio-button, frost-group, frost-scroll, frost-text, frost-textarea, frost-toggle
- **REWORK** API of frost-toggle, frost-link, frost-radio-button, frost-radio-group
- **UPDATED** general cleanup for destructing of `get`, `set`, `on` and `$`
- **UPDATED** existing component definitions to match recently updated generator.
- **UPDATED/ADDED** hooks and qualifiers on all the components
- **ADDED** a single export point at `addon/index.js`
- **REMOVED** all the unnecessary frost-icons
- **REMOVED** all the deprecated functionalities
- **REMOVED** unnecessary code
- **UPDATED** the dependencies
- **UPDATED** `baseURL` to `rootURL`
- **UPDATED** tests to run in chrome
- **UPDATED** `package.json` scripts
- **UPDATED** node version from >= 5 to >=6
- **FIXED** `ember-cli-code-coverage` version to 3.5.0
- **FIXED** all the sass linting issues
- **REMOVED** dependency to `one-way-controls`
- **ADDED** support for an inline version of frost-link
- **ADDED** support for small/medium/large radio-button `size`
- **ADDED** support for `required` and `error` for radio-button/radio-group
- **ADDED** support for an inline version of radio-group
- **ADDED** support for multiple routes on frost-link

### CODE REVIEW

**Comment by dafortin** [comment]
@juwara0 @rox163 @sglanzer anything you will like to add in the changelog?

**Comment by sglanzer-fire** [comment]
I'll take a final pass over this on Sunday - if anyone else wants to do a full pass as well I'd appreciate it.  Let's aim to land this Monday.

**Comment by sglanzer-fire** [comment]
https://github.com/ciena-frost/ember-frost-core/blob/1.0-beta/package.json#L164 this appears to be exclusive to ember-cli, any idea why it's in our dependencies?  Actually there are a number of dependencies here I'm curious about:

    "broccoli-file-creator": "^1.1.0",
    "broccoli-funnel": "^1.0.1",
    "broccoli-merge-trees": "^1.0.0",
    "broccoli-svgstore": "~0.3.1",
    "ember-browserify": "^1.1.13", -> I thought @sandersky had removed the need for this?
    "ember-cli-babel": "^5.1.6",
    "ember-cli-htmlbars": "^1.0.3",
    "ember-cli-normalize-entity-name": "^1.0.0",
    "ember-cli-path-utils": "^1.0.0",
    "ember-cli-sass": "^5.6.0",
    "ember-cli-string-utils": "^1.0.0",
    "ember-cli-valid-component-name": "^1.0.0",
    "ember-prop-types": "^3.0.0",
    "npm-install-security-check": "^1.0.0"

Got my answer to this - updated to just drop browserify

**Comment by sglanzer-fire** [comment]
https://github.com/ciena-frost/ember-frost-core/blob/1.0-beta/blueprints/ember-frost-core/index.js#L29 is only used for testing, not sure why we would put it in the blueprint since it comes with `ember-cli`

**Comment by sglanzer-fire** [comment]
Are we including test dependencies to ensure that projects using core also use these dependencies?  I'm not sure if I like this idea and even if we are why wouldn't we include something like `ember-cli-code-coverage` as well?

https://github.com/ciena-frost/ember-frost-core/blob/1.0-beta/blueprints/ember-frost-core/index.js#L34

**Comment by sglanzer-fire** [comment]
https://github.com/ciena-frost/ember-frost-core/blob/1.0-beta/blueprints/ember-frost-core/index.js#L27

No SASS and no prop-types?

**Comment by sglanzer-fire** [comment]
Let's remove this for now https://github.com/ciena-frost/ember-frost-core/blob/1.0-beta/package.json#L5

**Comment by sglanzer-fire** [comment]
Can we drop this? https://github.com/ciena-frost/ember-frost-core/blob/1.0-beta/package.json#L131

**Comment by sglanzer-fire** [comment]
And this? https://github.com/ciena-frost/ember-frost-core/blob/1.0-beta/package.json#L133

**Comment by sglanzer-fire** [comment]
https://github.com/ciena-frost/ember-frost-core/blob/1.0-beta/index.js#L100 perfect scrollbar has an npm package, can we drop the bower dependency and use npm instead?

https://www.npmjs.com/package/perfect-scrollbar

Even if we have to use a vendor import like https://github.com/ciena-frost/ember-frost-core/blob/1.0-beta/index.js#L96 I'd still prefer that

**Comment by sglanzer-fire** [comment]
I'd like to drop legacy support for icon packs in 1.0 https://github.com/ciena-frost/ember-frost-core/blob/1.0-beta/index.js#L179

**Comment by dafortin** [comment]
1) "ember-browserify": "^1.1.13",
Was removed in master but not in beta. I will remove it.
2) `ember-cli-normalize-entity-name`
We are using in blueprint (utils)
3) `ember-cli-path-utils`
We are using `getRelativeParentPath` in the blueprint. 
4) `ember-cli-string-utils`
We are using `dasherize` in the blueprint.
5) `ember-cli-valid-component-name`
We are using in blueprint (utils)

**Comment by sglanzer-fire** [comment]
I'd like to see a mention of the auto-generated class names for icons here (instead of adding a new class) https://github.com/ciena-frost/ember-frost-core/blob/1.0-beta/docs/frost-icons.md#set-the-fill-color-for-an-icon

**Comment by dafortin** [comment]
6) `ember-cli-htmlbars-inline-precompile`
I will remove it from blueprint.

**Comment by sglanzer-fire** [comment]
Sorry, what do you mean by (utils)?  And in the case of blueprint usage, can't we just include those as npm dependencies? (since they'll need to be present before running the blueprint anyway)?

Got my answer to this, updated the npm dependency comment

**Comment by dafortin** [comment]
> Are we including test dependencies to ensure that projects using core also use these dependencies? I'm not sure if I like this idea and even if we are why wouldn't we include something like ember-cli-code-coverage as well?

Should we remove that one?

**Comment by sglanzer-fire** [comment]
@job13er can you comment on the test packages in the blueprints?

**Comment by sglanzer-fire** [comment]
https://github.com/ciena-frost/ember-frost-core/blob/1.0-beta/config/ember-try.js#L98 we should have 2.8 in here

**Comment by dafortin** [comment]
> https://github.com/ciena-frost/ember-frost-core/blob/1.0-beta/blueprints/ember-frost-core/index.js#L27
No SASS and no prop-types?

Should we see SASS or prop types? I looked in `frost-tabs` and `frost-modal` and they are not there.

**Comment by sglanzer-fire** [comment]
@dafortin if we don't list them and install from scratch, will it work? (I don't think it will)

That begs the question, has anyone tried installing this against a new app?

**Comment by dafortin** [comment]
> Can we drop this? https://github.com/ciena-frost/ember-frost-core/blob/1.0-beta/package.json#L131

No it's used for the demo.

**Comment by dafortin** [comment]
> And this? https://github.com/ciena-frost/ember-frost-core/blob/1.0-beta/package.json#L133

We are using this for the syntax highly in the demo.

**Comment by rox163** [comment]
I think prop-types should be there but sass doesn't have to be there. I dont think Ive seen it in any of our blueprints at any time.

**Comment by dafortin** [comment]
Humm wait it think it might be a leftover

**Comment by sglanzer-fire** [comment]
@rox163 I assume it's working just off the strength of being in `dependencies` then

**Comment by rox163** [comment]
yes wrt sass

**Comment by sglanzer-fire** [comment]
We should probably only start including things in blueprints if they actually have a blueprint to run - slows down installs otherwise

**Comment by dafortin** [comment]
We are still using `markdown-code-highlighting` in our demo, but we can probably clean this up to use `code-snippet`.

**Comment by sglanzer-fire** [comment]
Ok, beyond those comments I believe I've seen enough of the interfaces to be satisfied that we aren't at high risk for a #major# after this.  There is cleanup to be done, but that's post-LTS

Any dependencies that are demo-only you can ignore for now as well

**Comment by rox163** [comment]
even if the addon doesnt have a blueprint to run, if core needs it and we want a consumer to have it , shouldn't we list it? Like `ember-hook`, which is in the blueprint

**Comment by sglanzer-fire** [comment]
If there is no blueprint to run, we can just list it in dependencies

**Comment by rox163** [comment]
hook doesnt have a blueprint at the moment. Same for prop-types.

**Comment by sglanzer-fire** [comment]
Ok great, then we don't need them in the blueprint, but we do need them in dependencies (ember-hook in particular is missing)

**Comment by dafortin** [comment]
I got the following items:
1) Use `code-snippet` instead of `markdown-code-highlighting`
2) User npm `perfect-scrollbar` dependency instead of bower
3) Drop legacy for icon
4) Improve example to auto generate class names instead of adding class in demo
5) Try to install in a new app
6) Move hook to dependencies and remove from blueprint

Anything else?

I already did the following:
1) Update ember-try file
2) `ember-cli-htmlbars-inline-precompile` removed from blueprint

**Comment by sglanzer-fire** [comment]
I don't mind delaying the removal of the markdown highlighter (sorry, couldn't help myself from commenting)

**Comment by sglanzer-fire** [comment]
Put the rest of my list in Slack

**Comment by dafortin** [comment]
Did the following in my last commit: 
* Remove bower dependency on `perfect-scrollbar`
* Remove `ember-browserify` dependency
* Move tests `devDependencies` to `dependencies`
* Remove unnecessary dependencies from blueprint
* Update `ember-try.js` with 2.8.0
* Update icon documentation
* Fix small issue with toggle tests

**Comment by dafortin** [comment]
Created issues for: https://github.com/ciena-frost/ember-frost-core/issues/314

**Comment by rox163** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-core/pull-request/310/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-core)

**Comment by sglanzer-fire** [comment]
Approved - LGTM

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-core/pull-request/310/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-core)

**Pull request merged**
