### PR TITLE
Fix ember-try config

### PR DESCRIPTION
**Pull request by juwara0**
**This project uses [semver](http://semver.org), please check the scope of this pr:**

- [X] #none# - documentation fixes and/or test additions
- [ ] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG
* **Updated** ember-try config

### CODE REVIEW

**Comment by quincyle** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-core/pull-request/480/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-core)

**Comment by EWhite613** [comment]
Problem is this line in the 2.8 test https://github.com/ciena-frost/ember-frost-core/blob/master/ember-cli-build.js#L27

Need to change it to programmatically bower_components location(if there's no `ember-source` 
and import from there. Since currently, it's getting it from `ember-source` (even if ember-source doesn't exist)

**Comment by EWhite613** [comment]
Same goes for https://github.com/ciena-frost/ember-frost-bunsen/pull/460

**Comment by EWhite613** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-core/pull-request/480/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-core)

**Comment by EWhite613** [comment]
@juwara0 think you need to pin the `ember-try` version like @quincyle  does here https://github.com/ciena-frost/ember-frost-bunsen/pull/460/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R79 to avoid the yarn bug

**Comment by juwara0** [comment]
NOTE: We modified the ember-try config to use Ember 2.8 instead of Ember LTS 2.8 due to a difference in behavior when running `frost-link` in these two versions:  https://github.com/ciena-frost/ember-frost-core/issues/481

**Comment by juwara0** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-core/pull-request/480/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-core)

**Pull request merged**
