### PR TITLE
remove test blueprints

### PR DESCRIPTION
**Pull request by juwara0**
* **Removed** test blueprints since they change the convention of the rest of the tests.

---
This change is [Reviewable](https://reviewable.io/reviews/ciena-frost/ember-frost-core/271)

### CODE REVIEW

**Comment by rox163** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-core/pull-request/271/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-core)

**Comment by rox163** [comment]
is there an issue open to track adding of these back in?

**Comment by sglanzer-fire** [comment]
I'd much rather see replacement than removal, I assume you have a format in mind?

**Comment by juwara0** [comment]
What I would like is to change the direction of the test blueprints. We do not want to delete them completely but rather alter them. I am going to close this PR until we have a discussion to decide what those changes should entail.

**Pull request closed without merging**
