### PR TITLE
Fix Major Memory Leak by Uninitializing Perfect Scroll When Cleaning Up

### PR DESCRIPTION
**Pull request by sophypal**
**This project uses [semver](http://semver.org), please check the scope of this pr:**

- [x] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG

* **Fixes** a major memory leak in `frost-scroll`

### CODE REVIEW

**Comment by juwara0** [comment]
Thank you for this PR but this has already been fixed in the 1.0-beta branch that we are preparing for release: https://github.com/ciena-frost/ember-frost-core/blob/1.0-beta/addon/components/frost-scroll.js#L115

**Comment by juwara0** [comment]
You can find the included fix mentioned above in the following PR: https://github.com/ciena-frost/ember-frost-core/pull/310/files#diff-6311ca3d626b2bcaf9f3ca6a515eaae0

**Comment by sglanzer-fire** [comment]
Might make sense to merge this anyway for anyone remaining on the pre-1.x stream for a period of time

**Comment by sglanzer-fire** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-core/pull-request/311/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-core)

**Pull request merged**
